platform :ios, '8.0'

target 'IMNIMDemo' do
    pod 'SDWebImage', '~> 4.2.2'
    pod 'Toast', '~> 3.0'
    pod 'M80AttributedLabel', '~> 1.6.3'
    pod 'TZImagePickerController', '~> 1.9.3'
    pod 'FMDB', '~> 2.7.2'
    pod 'Reachability', '~> 3.2'
    pod 'CocoaLumberjack', '~> 3.2.1'
    pod 'SSZipArchive', '~> 1.8.1'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'Fabric'
    pod 'Crashlytics'
end
